num_workers: 4
pin_memory: True
non_blocking: True
prefetch: False
amp: False
device: cuda:1
client_optimizer: sgd
dataset: cifar10
dataset_path: ../data
frequency_save: 0
batch_size: 1024
lr: 0.1
lr_scheduler: CosineAnnealingLR
model: resnet18
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
epochs: 100
split_ratio: 0.02
