name: classification

data:
  data_root: data/mnist
  dataset: mnist
  batch_size: 64
  num_workers: 1

# model for data
model:
  _target_: models.resnet.ResNet18
  num_classes: 10
  input_channel: 1

# optimizer for training task model
optimizer:
  _target_: torch.optim.SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

# lr scheduler for training task optimizer
lr_scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones: [30, 60, 90, 100]
  gamma: 0.2

epoch: 100
save_num_model: 200
train_layer: ['layer4.1.bn1.weight', 'layer4.1.bn1.bias', 'layer4.1.bn2.bias', 'layer4.1.bn2.weight']

# parameter data root
param:
  data_root: param_data/mnist/data.pt
  k: 200
  num_workers: 4
